-- 股票 AI 助理 v18.1：Top5 推薦績效歷史
-- 請先在 Supabase SQL Editor 執行一次。

create table if not exists public.ai_recommend_history (
    id bigint generated by default as identity primary key,
    scan_date date not null,
    symbol varchar(10) not null,
    name varchar(100) default '',
    market varchar(10) default 'TWSE',
    rank integer not null,
    score_version varchar(30) default 'AI Score 2.0',
    ai_score integer not null default 0,
    trend_score integer not null default 0,
    momentum_score integer not null default 0,
    volume_score integer not null default 0,
    risk_score integer not null default 0,
    position_score integer not null default 0,
    entry_price numeric(18,4) not null,
    day1_date date,
    day1_price numeric(18,4),
    day1_return numeric(12,4),
    day5_date date,
    day5_price numeric(18,4),
    day5_return numeric(12,4),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint ai_recommend_history_scan_symbol_uk unique (scan_date, symbol)
);

create index if not exists idx_ai_recommend_history_scan_date
    on public.ai_recommend_history (scan_date desc);

create index if not exists idx_ai_recommend_history_pending_day1
    on public.ai_recommend_history (scan_date)
    where day1_price is null;

create index if not exists idx_ai_recommend_history_pending_day5
    on public.ai_recommend_history (scan_date)
    where day5_price is null;

create or replace function public.set_ai_recommend_history_updated_at()
returns trigger language plpgsql as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists trg_ai_recommend_history_updated_at on public.ai_recommend_history;
create trigger trg_ai_recommend_history_updated_at
before update on public.ai_recommend_history
for each row execute function public.set_ai_recommend_history_updated_at();
